include:
  - project: sre/gitlab-ci-templates
    ref: v1
    file:
      - /shared/deploy-kubefiles.yml
      - /shared/upload-to-aliyun-oss.yml
  - .gitlab/.gitlab-ci.mixin.yml

stages:
  - build
  - upload
  - deploy
  - notification

# 国内 构建
build_cn:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_cn_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
        APP_ROUTER_BASE_URL: /tapsdk-doc-cn-$CI_MERGE_REQUEST_ID/
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        APP_PUBLIC_PATH: https://developer.taptap.cn
        APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-cn:preview
  artifacts:
    paths:
      - cn/build

upload_assets_cn:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_cn_rule
  variables:
    GIT_STRATEGY: none
    ALIYUN_OSS_BUCKET: tap-assets-cn
    ALIYUN_OSS_ENDPOINT: oss-accelerate.aliyuncs.com
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        SRC_PATH: cn/build
        DEST_PATH: apps/tap-sdk-doc/mr/tapsdk-doc-cn-$CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SRC_PATH: cn/build
        DEST_PATH: apps/tap-sdk-doc/prod
  needs:
    - build_cn

mr_slack_cn:
  stage: notification
  extends: .mixin_slack
  variables:
    BUILD_LOCATION: cn
  needs:
    - upload_assets_cn

build_rnd:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_cn_rule
  when: manual
  variables:
      APP_PUBLIC_PATH: https://developer.xdrnd.cn
      APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-cn:preview
  artifacts:
    paths:
      - cn/build

upload_assets_rnd:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_cn_rule
  variables:
    ALIYUN_OSS_BUCKET: tap-assets-cn
    ALIYUN_OSS_ENDPOINT: oss-accelerate.aliyuncs.com
    SRC_PATH: cn/build
    DEST_PATH: apps/tap-sdk-doc/rnd/cn
  needs:
    - build_rnd


# hk 构建
build_hk:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_hk_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
        APP_ROUTER_BASE_URL:  /tapsdk-doc-hk-$CI_MERGE_REQUEST_ID/
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        APP_PUBLIC_PATH: https://developer.taptap.cn
        APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-hk:preview
  artifacts:
    paths:
      - hk/build

upload_assets_hk:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_hk_rule
  variables:
    GIT_STRATEGY: none
    ALIYUN_OSS_BUCKET: tap-assets-cn
    ALIYUN_OSS_ENDPOINT: oss-accelerate.aliyuncs.com
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        SRC_PATH: hk/build
        DEST_PATH: apps/tap-sdk-doc/mr/tapsdk-doc-hk-$CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SRC_PATH: hk/build
        DEST_PATH: apps/tap-sdk-doc/prod
  needs:
    - build_hk

mr_slack_hk:
  stage: notification
  extends: .mixin_slack
  variables:
    BUILD_LOCATION: hk
  needs:
    - upload_assets_hk


deploy_rnd_hk:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_hk_rule
  variables:
    ALIYUN_OSS_BUCKET: tap-assets-cn
    ALIYUN_OSS_ENDPOINT: oss-accelerate.aliyuncs.com
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SRC_PATH: hk/build
        DEST_PATH: apps/tap-sdk-doc/rnd
  needs:
    - build_hk