include:
  - project: sre/gitlab-ci-templates
    ref: v1
    file:
      - /shared/build-and-push-image.yml
      - /shared/deploy-kubefiles.yml
      - /shared/upload-to-aliyun-oss.yml
  - .gitlab/.gitlab-ci.mixin.yml

stages:
  - build
  - upload
  - deploy
  - notification

# 国内 构建
build_cn:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_cn_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
        APP_ROUTER_BASE_URL: /tapsdk-doc-cn-$CI_MERGE_REQUEST_ID/
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        APP_PUBLIC_PATH: https://developer.taptap.cn
        APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-cn:preview
  artifacts:
    paths:
      - cn/build

upload_mr_assets_cn:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_cn_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    ALIYUN_OSS_BUCKET: tds-abd-sh
    ALIYUN_OSS_ENDPOINT: oss-cn-shanghai-internal.aliyuncs.com
    SRC_PATH: cn/build
    DEST_PATH: preview/tapsdk-doc-cn-$CI_MERGE_REQUEST_ID
  needs:
    - build_cn

mr_slack_cn:
  stage: notification
  extends: .mixin_slack
  variables:
    BUILD_LOCATION: cn
    APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
    APP_ROUTER_BASE_URL: /tapsdk-doc-cn-$CI_MERGE_REQUEST_ID/
  needs:
    - upload_mr_assets_cn

# hk 构建
build_hk:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_hk_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
        APP_ROUTER_BASE_URL:  /tapsdk-doc-intl-$CI_MERGE_REQUEST_ID/
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        APP_PUBLIC_PATH: https://developer.taptap.cn
        APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-hk:preview
  artifacts:
    paths:
      - hk/build

upload_mr_assets_hk:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_hk_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    GIT_STRATEGY: none
    ALIYUN_OSS_BUCKET: tds-abd-sh
    ALIYUN_OSS_ENDPOINT: oss-cn-shanghai-internal.aliyuncs.com
    SRC_PATH: hk/build
    DEST_PATH: preview/tapsdk-doc-intl-$CI_MERGE_REQUEST_ID
  needs:
    - build_hk

mr_slack_hk:
  stage: notification
  extends: .mixin_slack
  variables:
    BUILD_LOCATION: hk
    APP_PUBLIC_PATH: https://tds-preview.xdrnd.cn
    APP_ROUTER_BASE_URL:  /tapsdk-doc-intl-$CI_MERGE_REQUEST_ID/
  needs:
    - upload_mr_assets_hk


# docker build cn
docker_upload_cn:
  stage: upload
  extends: 
    - .mixin_cn_rule
    - .build-and-push-image
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    DOCKER_REGISTRY_REPO: tapsdk-doc/cn
    DOCKERFILE: cn.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_cn
  dependencies:
    - build_cn

deploy_cn:
  stage: deploy
  extends: 
    - .deploy-kubefiles-production
  environment:
    name: cn/production
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUE_FILENAME: bj_values.yaml
  needs:
    - docker_upload_cn
  when: manual

# docker build hk
docker_upload_hk:
  stage: upload
  extends: 
    - .mixin_hk_rule
    - .build-and-push-image
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    DOCKER_REGISTRY_REPO: tapsdk-doc/hk
    DOCKERFILE: hk.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_hk
  dependencies:
    - build_hk

deploy_hk:
  stage: deploy
  extends: 
    - .deploy-kubefiles-production
  environment:
    name: hk/production
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUE_FILENAME: hk_values.yaml
  needs:
    - docker_upload_hk
  when: manual


# docker build cn rnd
build_rnd_cn:
  when: manual
  stage: build
  extends: 
    - .mixin_build
    - .mixin_cn_rule
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    APP_PUBLIC_PATH: https://developer.xdrnd.cn
    APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-cn:preview
  artifacts:
    paths:
      - cn/build

docker_upload_rnd_cn:
  stage: upload
  extends: 
    - .mixin_cn_rule
    - .build-and-push-image
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-cn
    DOCKERFILE: cn.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_rnd_cn
  dependencies:
    - build_rnd_cn

deploy_rnd_cn:
  stage: deploy
  extends: 
    - .mixin_cn_rule
    - .deploy-kubefiles-staging
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  environment:
    name: cn/staging
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUE_FILENAME: rnd_values.yaml
  needs:
    - docker_upload_rnd_cn
  when: manual


  # docker build hk rnd
build_rnd_hk:
  when: manual
  stage: build
  extends: 
    - .mixin_build
    - .mixin_hk_rule
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    APP_PUBLIC_PATH: https://developer-intl.xdrnd.com
    APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-hk:preview
  artifacts:
    paths:
      - hk/build

docker_upload_rnd_hk:
  stage: upload
  extends: 
    - .mixin_hk_rule
    - .build-and-push-image
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    DOCKER_REGISTRY_NAMESPACE: web-frontend
    DOCKER_REGISTRY_REPO: tapsdk-doc-intl
    DOCKERFILE: hk.Dockerfile
    DOCKER_BUILD_PATH: .
  needs:
    - build_rnd_hk
  dependencies:
    - build_rnd_hk

deploy_rnd_hk:
  stage: deploy
  extends: 
    - .mixin_hk_rule
    - .deploy-kubefiles-staging
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  environment:
    name: staging
  variables:
    PROJECT_PATH: tds/tapsdkdoc
    VALUE_FILENAME: rnd_intl_values.yaml
  needs:
    - docker_upload_rnd_hk
  when: manual
