include:
  - project: sre/gitlab-ci-templates
    ref: v1
    file:
      - /shared/build-and-push-image.yml
      - /shared/deploy-kubefiles.yml
      - /shared/upload-to-aliyun-oss.yml
  - .gitlab/.gitlab-ci.mixin.yml

variables:
  ALIYUN_OSS_BUCKET: tds-abd-sh
  ALIYUN_OSS_ENDPOINT: oss-cn-shanghai-internal.aliyuncs.com

stages:
  - build
  - upload
  - deploy

# 国内预览环境构建
build_mr_cn:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_cn_rule
  variables:
    PREVIEW_PREFIX: tapsdk-doc-cn
  script:
    - source ./scripts/make-preview.sh preview
    - yarn run build-cn:preview
  artifacts:
    paths:
      - cn/build

upload-assets-mr-cn:
  stage: upload
  extends: .mixin_upload
  variables:
    SRC_PATH: cn/build
    DEST_PATH: preview/tapsdk-doc-cn-$CI_MERGE_REQUEST_ID
  needs:
    - build_mr_cn

mr_slack_cn:
  stage: upload
  extends: .mixin_slack
  variables:
    PREVIEW_PREFIX: tapsdk-doc-cn
    BUILD_LOCATION: cn
  needs:
    - upload-assets-mr-cn

# hk预览环境构建
build_mr_hk:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_hk_rule
  variables:
    PREVIEW_PREFIX: tapsdk-doc-intl
  script:
    - source ./scripts/make-preview.sh preview
    - yarn run build-hk:preview
  artifacts:
    paths:
      - hk/build

upload-assets-mr-hk:
  stage: upload
  extends: .mixin_upload
  variables:
    SRC_PATH: hk/build
    DEST_PATH: preview/tapsdk-doc-intl-$CI_MERGE_REQUEST_ID
  needs:
    - build_mr_hk

mr_slack_hk:
  stage: upload
  extends: .mixin_slack
  variables:
    PREVIEW_PREFIX: tapsdk-doc-intl
    BUILD_LOCATION: intl
  needs:
    - upload-assets-mr-hk

# cn线上环境构建
build_cn:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_cn_rule
  script:
    - yarn run build-cn
  artifacts:
    paths:
      - cn/build
  only:
    - master

upload-assets-cn:
  stage: upload
  needs:
    - build_cn
  only:
    - master
  interruptible: true
  extends:
    - .upload-to-aliyun-oss
    - .mixin_cn_rule
  variables:
    ALIYUN_OSS_BUCKET: tap-assets-cn
    ALIYUN_OSS_ENDPOINT: oss-cn-beijing.aliyuncs.com
    SRC_PATH: others/developer-center/dist
    DEST_PATH: dview

# deploy rnd
deploy-staging:
  stage: deploy
  extends: 
    - .deploy-kubefiles-staging
    - .mixin_cn_rule
  variables:
    PROJECT_PATH: tds/tapsdkdoc
  when: on_success
  only:
    - master

# deploy 线上
deploy-cn:
  stage: deploy
  extends: 
    - .deploy-kubefiles-production
    - .mixin_cn_rule
  variables:
    PROJECT_PATH: tds/tapsdkdoc
  when: on_success
  only:
    - master



