include:
  - project: sre/gitlab-ci-templates
    ref: v1
    file:
      - /shared/deploy-kubefiles.yml
      - /shared/upload-to-aliyun-oss.yml
  - .gitlab/.gitlab-ci.mixin.yml

stages:
  - build
  - upload
  - deploy

# 国内 构建
build_cn:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_cn_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        CDN_PATH: https://assets.tapimg.com/apps/tap-sdk-doc/mr/cn/$CI_MERGE_REQUEST_ID
        APP_PUBLIC_PATH: https://developer.xdrnd.com
        APP_ROUTER_BASE_URL: /docs/tapsdk-cn-$CI_MERGE_REQUEST_ID/
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        CDN_PATH: https://assets.tapimg.com/apps/tap-sdk-doc/prod
        APP_PUBLIC_PATH: https://developer.taptap.cn
        APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-cn:preview
  artifacts:
    paths:
      - cn/build

upload_assets_cn:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_cn_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        SRC_PATH: cn/build
        DEST_PATH: apps/tap-sdk-doc/mr/cn/$CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SRC_PATH: cn/build
        DEST_PATH: apps/tap-sdk-doc/prod
  needs:
    - build_cn

mr_slack_cn:
  stage: upload
  extends: .mixin_slack
  variables:
    BUILD_LOCATION: cn
  needs:
    - upload_assets_cn

deploy_rnd_cn:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_cn_rule
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SRC_PATH: cn/build
        DEST_PATH: apps/tap-sdk-doc/rnd
  needs:
    - build_cn


# hk 构建
build_hk:
  stage: build
  extends: 
    - .mixin_build
    - .mixin_hk_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        CDN_PATH: https://assets.tapimg.com/apps/tap-sdk-doc/mr/hk/$CI_MERGE_REQUEST_ID
        APP_PUBLIC_PATH: https://developer.xdrnd.com
        APP_ROUTER_BASE_URL: /docs/tapsdk-hk-$CI_MERGE_REQUEST_ID/
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        CDN_PATH: https://assets.tapimg.com/apps/tap-sdk-doc/prod
        APP_PUBLIC_PATH: https://developer.taptap.cn
        APP_ROUTER_BASE_URL: /docs/
  script:
    - yarn run build-hk:preview
  artifacts:
    paths:
      - hk/build

upload_assets_hk:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_hk_rule
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        SRC_PATH: hk/build
        DEST_PATH: apps/tap-sdk-doc/mr/hk/$CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SRC_PATH: hk/build
        DEST_PATH: apps/tap-sdk-doc/prod
  needs:
    - build_hk

mr_slack_hk:
  stage: upload
  extends: .mixin_slack
  variables:
    BUILD_LOCATION: intl
  needs:
    - upload_assets_hk


deploy_rnd_hk:
  stage: upload
  extends: 
    - .mixin_upload
    - .mixin_hk_rule
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SRC_PATH: hk/build
        DEST_PATH: apps/tap-sdk-doc/rnd
  needs:
    - build_hk