.mix_install_deps:
  interruptible: true
  image: registry.tapsvc.com/public/node18-buster:pnpm7.27.0-1.0.0
  tags:
    - node
  before_script:
    - npm config set registry https://nexus.tapsvc.com/repository/npm-taptap
    - export NODE_OPTIONS=--max_old_space_size=4096
    - yarn install --cache-folder .yarn-cache
  cache:
    - key:
        files:
          - yarn.lock
          - .npmrc
      paths:
        - .yarn-cache

.mixin_build:
  stage: build
  interruptible: true
  environment:
    name: independent
  extends:
    - .mix_install_deps
  artifacts:
    expire_in: 1 week

.mixin_upload:
  stage: image-assets
  environment:
    name: independent
  variables:
    GIT_STRATEGY: none
  extends:
    - .upload-to-aliyun-oss

.mixin_slack:
  extends:
    - .mix_install_deps
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - git --version
    - npm i -g zx
    - source ./scripts/slack-definition.sh
    - chmod -R 777 ./scripts && ./scripts/slack-notification
  
