.mix_install_deps:
  interruptible: true
  image: taptap-img-registry.cn-beijing.cr.aliyuncs.com/public/node-abd-common:4.0.0
  before_script:
    - export NODE_OPTIONS=--max_old_space_size=4096
    - yarn install

.mixin_except_lokalise:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.default_build:
  stage: build
  interruptible: true
  environment:
    name: independent
  extends:
    - .mix_install_deps
    - .mixin_except_lokalise
  rules:
    - changes:
        - "**/*"
  artifacts:
    expire_in: 1 week

.default_upload:
  stage: image-assets
  environment:
    name: independent
  variables:
    GIT_STRATEGY: none
  extends:
    - .upload-to-aliyun-oss
    - .mixin_except_lokalise

.default_slack:
  stage: version
  extends:
    - .mix_install_deps
    - .mixin_except_lokalise
  script:
    - source ./scripts/slack-definition.sh
    - chmod -R 777 ./scripts && ./scripts/slack-notification
  when: manual